# config.yml

app:
  debug_status: true
  number_of_workers: 10

server:
  address: "127.0.0.1:8080"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s

jwt:
  expire: 3 # hours
  secret: "ABOBA"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "123"
  dbname: "postgres"
  sslmode: "disable"
  max_connections: 20
  max_idle_connections: 5
  conn_path: "postgres://postgres:123@localhost:5432/postgres"
  dsn: "host=localhost user=postgres password=123 dbname=postgres port=5432 sslmode=disable"

security:
  jwt_secret: "supersecretkey"
  token_expiry: 24h
  allowed_origins:
    - "https://app.example.com"
    - "https://admin.example.com"

  accrual:
    address: "http://127.0.0.1:8081"