core:
  debug_mode: true
  config_path: "./config.yml"

server:
  host: "0.0.0.0"
  port: 8080
  addr: "0.0.0.0:8080"

db:
  host: "db"
  port_ro: 5432
  port_rw: 5432
  user: "postgres"
  password: "postgres"
  encode: "utf8"
  dbname: "postgres"
  max_conn_active: 20
  max_idle_conns: 5
  conn_max_lifetime: 30m
  dsn: "host=db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"

jwt:
  secret: "ABOBA"
  jwt_lifetime: 3h
  issuer: "my-app"
  refresh:
    lifetime: 720h   # 30 days
    length: 64

logger:
  level: "debug"